### ISSUE TITLE
nieobsłużony wyjątek

### ISSUE THREAD

**Issue by jzawadzki** [radoslawkoziol/Casper#1]
Cześć,

https://github.com/radoslawkoziol/Casper/blob/master/src/Polcode/CasperBundle/Controller/EventController.php#L10-L12
jeśli nie będzie eventu o danym 'slugu' to kod zwróci wyjątek, a powinien 404
JZ

**Comment by radoslawkoziol** [comment]
Cześć,

Okej, dzięki przeoczyłem to, poprawię.

Pozdrawiam

10.03.2015, Jerzy Zawadzki <notifications@github.com> napisał(a):
> Cześć,
>
> https://github.com/radoslawkoziol/Casper/blob/master/src/Polcode/CasperBundle/Controller/EventController.php#L10-L12
> jeśli nie będzie eventu o danym 'slugu' to kod zwróci wyjątek, a powinien
> 404
> JZ
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/radoslawkoziol/Casper/issues/1


-- 
Radosław Kozioł
PHP Developer

Polcode SA
13 Hoza Street, 00-528 Warsaw, Poland
http://www.polcode.com/
T: +48 22 825 50 47

Company listed in the Register of Entrepreneurs of the National Court
Register maintained by the District Court of Warsaw, XII Commercial
Division under the number 482235, VAT PL 7010217288, initial capital PLN
300,000 fully paid.
